VLTECH/Models/Donhang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLTECH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donhang()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
        }
    
        public int Madon { get; set; }
        public Nullable<System.DateTime> Ngaydat { get; set; }
        public Nullable<int> MaNguoidung { get; set; }
        public Nullable<int> Matt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual Nguoidung Nguoidung { get; set; }
        public virtual Tinhtrang Tinhtrangs { get; set; }

        public virtual ICollection<sp_baocao_thang_Result> Baocaos { get; set; }
        public virtual ICollection<sp_baocao_ngay_Result> Baocaongays { get; set; }
    }
}

VLTECH/Areas/Admin/Controllers/DonhangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VLTECH.Models;
using PagedList;

namespace VLTECH.Areas.Admin.Controllers
{
    public class DonhangsController : BaseController
    {
        private Qlbanhang db = new Qlbanhang();

        // GET: Admin/Donhangs
        public ActionResult Index(int? page, string search)
        {
            // 1. Tham số int? dùng để thể hiện null và kiểu int( số nguyên)
            // page có thể có giá trị là null ( rỗng) và kiểu int.

            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            // 3. Tạo truy vấn sql, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo Masp mới có thể phân trang.
            var sp = db.Donhangs.OrderBy(x => x.Madon);

            // 4. Tạo kích thước trang (pageSize) hay là số sản phẩm hiển thị trên 1 trang
            int pageSize = 5;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các sản phẩm được phân trang theo kích thước và số trang.
            return View(db.Donhangs.Where(x => x.Madon.ToString().Contains(search) || x.Nguoidung.Dienthoai.ToString().Contains(search) || search == null).ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Donhangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donhang donhang = db.Donhangs.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNguoidung = new SelectList(db.Nguoidungs, "MaNguoiDung", "Hoten", donhang.MaNguoidung);
            ViewBag.Matt = new SelectList(db.Tinhtrangs, "Matt", "Tinhtrangdonhang", donhang.Matt);
            return View(donhang);
        }

        // POST: Admin/Donhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Madon,Ngaydat,MaNguoidung,Matt")] Donhang donhang)
        {
            if (ModelState.IsValid)
            {
                var oldItem = db.Donhangs.Find(donhang.Madon);
                oldItem.Matt = donhang.Matt;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNguoidung = new SelectList(db.Nguoidungs, "MaNguoiDung", "Hoten", donhang.MaNguoidung);
            ViewBag.Matt = new SelectList(db.Tinhtrangs, "Matt", "Tinhtrangdonhang", donhang.Matt);
            return View(donhang);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VLTECH/Controllers/DonHangController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VLTECH.Models;

namespace VLTECH.Controllers
{
    public class DonHangController : Controller
    {
        private Qlbanhang db = new Qlbanhang();

        // GET: Donhangs
        // Hiển thị danh sách đơn hàng
        public ActionResult Index(int? page)
        {
            //Kiểm tra đang đăng nhập
            if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "User");
            }
            // 1. Tham số int? dùng để thể hiện null và kiểu int( số nguyên)
            // page có thể có giá trị là null ( rỗng) và kiểu int.
            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            // 3. Tạo truy vấn sql, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            //// theo Masp mới có thể phân trang.
            Nguoidung kh = (Nguoidung)Session["use"];
            int maND = kh.MaNguoiDung;
            var sp = db.Donhangs.OrderBy(x => x.Madon).Include(d => d.Nguoidung).Where(d => d.MaNguoidung == maND);
            //var sp = db.Donhangs.OrderBy(x => x.Madon);
            // 4. Tạo kích thước trang (pageSize) hay là số sản phẩm hiển thị trên 1 trang
            int pageSize = 15;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các sản phẩm được phân trang theo kích thước và số trang.
            return View(sp.ToPagedList(pageNumber, pageSize));

            //Nguoidung kh = (Nguoidung)Session["use"];
            //int maND = kh.MaNguoiDung;
            //var donhangs = db.Donhangs.Include(d => d.Nguoidung).Where(d => d.MaNguoidung == maND);
            //return View(donhangs.ToList());
        }

        // GET: Donhangs/Details/5
        //Hiển thị chi tiết đơn hàng
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donhang donhang = db.Donhangs.Find(id);
            var chitiet = db.Chitietdonhangs.Include(d => d.Sanpham).Where(d => d.Madon == id).ToList();
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(chitiet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VLTECH/Areas/Admin/Views/Donhangs/Edit.cshtml
@model VLTECH.Models.Donhang
   @{
        Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
        decimal? Tongtien = 0;
    }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chi tiết đơn hàng - @Html.DisplayFor(model => model.Madon) </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Madon)

        <div class="form-group">
            <b>Ngày đặt:</b> @Html.DisplayFor(model => model.Ngaydat)
        </div>

        <div class="form-group">
            <b>Tên khách hàng:</b> @Html.DisplayFor(model => model.Nguoidung.Hoten)
        </div>
        <table class="table table-bordered" style="text-align: center;">
            <tr>
                <th>
                    Sản phẩm
                </th>
                <th>
                    Số lượng
                </th>
                <th>
                    Đơn giá / 1 sản phẩm
                </th>
                <th>
                    Ảnh sản phẩm
                </th>
                <th>
                    Thành tiền
                </th>
            </tr>

            @foreach (var item in Model.Chitietdonhangs)
            {
                Tongtien += item.Thanhtien;
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sanpham.Tensp)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Soluong)
                    </td>
                    <td>
                        @String.Format("{0:0,0}", item.Dongia) VNĐ
                    </td>
                    <td>
                        <img src="@Url.Content(item.Sanpham.Anhbia)" width="50" height="50" />
                    </td>
                    <td>
                        @String.Format("{0:0,0}", item.Thanhtien) VNĐ
                    </td>
                </tr>
            }
            <tr>
                <td colspan="3" style="text-align:left; font-size: medium;"></td>
                <td colspan="1" style="text-align:left; font-size: medium; text-align:center">
                    <b>TỔNG TIỀN</b> 
                </td>
                <td colspan="1" style="text-align: left; font-size: medium; text-align: center">
                     @String.Format("{0:0,0}", @Tongtien) VNĐ
                </td>
            </tr>
        </table>
        <div class="form-group">
            <b>Tình trạng đơn hàng</b>
            @Html.DropDownList("Matt", null, "Đang chờ xác nhận", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Matt, "", new { @class = "text-danger" })
        </div>
        <div style="text-align: center;">
            <input type="submit" value="Save" class="btn btn-default" style="background-color: #179d02; color:#ffffff; text-decoration: none " />
            <div class="btn btn-default" style="background-color: #ff0000; text-decoration: none;">@Html.ActionLink("Back to List", "Index")</div>
        </div>
    </div>
    }

</body>
</html>

<style>
    .btn-default{
        width: 135px;
    }
    .a {
        color: #ffffff;
    }
</style>

VLTECH/Areas/Admin/Views/Donhangs/Index.cshtml
@model PagedList.IPagedList <VLTECH.Models.Donhang>

@using PagedList.Mvc;

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<!DOCTYPE html>

<style>

    .page-list {
        position: absolute;
        bottom: 230px;
        text-align: center;
    }
        .page-list a {
            color: #000000;
        }
    
</style>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>Quản lý đơn hàng </h2>
    @using (@Html.BeginForm("Index", "Donhangs", FormMethod.Get))
    {
        <div class="input-group" style="width: 400px;">
            @Html.TextBox("search", null, new { @class = "form-control", @type = "text", @placeholder = "Search for..." })
            <button class="btn btn-primary" type="submit" value="search"><i class="fas fa-search"></i></button>
        </div>
    }
    </br>
    <table class="table table-bordered" style="text-align:center">
        <tr>
            <th>
                Mã đơn
            </th>
            <th>
                Ngày đặt
            </th>
            <th>
                Họ tên khách hàng
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Tình trạng đơn hàng
                <i class="fa-solid fa-pen-to-square" style="width: 500px; background-color: red"></i>
            </th>
            <th>
                Hành động
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Madon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ngaydat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nguoidung.Hoten)
                </td>
                                <td>
                    @Html.DisplayFor(modelItem => item.Nguoidung.Dienthoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tinhtrangs.Tinhtrangdonhang)
                </td>
                <td>
                    <div style="text-align: center;">
                        <div class="btn btn-default" style="background-color: #179d02; ">@Html.ActionLink("Chi tiết và xác nhận", "Edit", new { id = item.Madon })</div>
                    </div>
                </td>
            </tr>
        }

    </table>
    <div class="page-list">
        @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount*@
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = Request.QueryString["search"] }))
    </div>
</body>
</html>