VLTECH/Areas/Admin/Controllers/BaocaosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using VLTECH.Models;


namespace VLTECH.Areas.Admin.Controllers
{
    public class BaocaosController : BaseController
    {
        private Qlbanhang db = new Qlbanhang();
        public ActionResult Index(int? thang)
        {
            var data = db.sp_baocao_thang(thang).ToList();
            return View(data);
        }
    }
}

VLTECH/Areas/Admin/Views/Baocaos/Index.cshtml
@model IEnumerable<VLTECH.Models.sp_baocao_thang_Result>
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    decimal? Tongtien = 0;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>

</head>



<body>
    <br />
    <h2>Quản lý báo cáo </h2>
    <p>
        <button class="btn-default" style="width: 245px; height: 50px; background-color: #179d02; color: #ffffff; border-radius: 5px; border: none;">@Html.ActionLink("Thống kê theo ngày", "Index", "Baocaongays")</button>
    </p>
    <p>
        @using (@Html.BeginForm("Index", "Baocaos", FormMethod.Get))
        {
            <h5>Chọn tháng</h5>
            @Html.DropDownList("thang", new SelectList(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 })) <input type="submit" value="Thống kê" />;
        }
    </p>



    <table class="table table-bordered" style="text-align: center;">
        <tr>

            <th>
                Ngày đặt
            </th>
            <th>
                Mã đơn
            </th>
            
            <th>
                Tên khách hàng
            </th>
            
            
            <th>
                Thành tiền
            </th>
        </tr>
        @foreach (var item in Model)
        {
            Tongtien += item.Thanhtien;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ngaydat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Madon)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Hoten)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Thanhtien)
                </td>

            </tr>
        }

    </table>
    </br>
    <div class="txt-summary" style="font-size: large;">
        <b>TỔNG DOANH THU:</b>
        @String.Format("{0:0,0}", @Tongtien) VNĐ
    </div>


</body>
</html>